server:
  port: 8761
spring:
  application:
    name: craft-enreka-server-ha
eureka:
  instance:
    hostname: peer2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer1:8760/eureka/